[2025-05-18 02:51:24] [error] ОШИБКА в задаче 2: MainBot.__init__() got an unexpected keyword argument 'proxy'
