[2025-05-18 03:50:19] [error] ОШИБКА в задаче 2: 'MainBot' object has no attribute '_get_proxy_url'
