[2025-05-18 02:51:57] [error] [BOT 0] Fatal error: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6381010>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
Traceback (most recent call last):
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 96, in start
    streams = await asyncio.get_event_loop().run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "c:\Program Files\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 98, in <lambda>
    lambda: self.streamlink.streams(f"https://www.twitch.tv/{self.channel}")
            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\session.py", line 153, in streams
    return plugin.streams(**params)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugin\plugin.py", line 401, in streams
    ostreams = self._get_streams()
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 986, in _get_streams
    return self._get_hls_streams_live()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 915, in _get_hls_streams_live
    sig, token, restricted_bitrates = self._access_token(True, self.channel)
                                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 884, in _access_token
    response, *data = self.api.access_token(is_live, channel_or_vod)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 516, in access_token
    return self.call(
           ~~~~~~~~~^
        query,
        ^^^^^^
    ...<29 lines>...
        ),
        ^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 314, in call
    return self.session.http.post(
           ~~~~~~~~~~~~~~~~~~~~~~^
        "https://gql.twitch.tv/gql",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\http.py", line 196, in request
    raise err from None  # TODO: fix this
    ^^^^^^^^^^^^^^^^^^^
streamlink.exceptions.PluginError: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6381010>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
[2025-05-18 02:51:58] [error] [BOT 1] Fatal error: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6841E50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
Traceback (most recent call last):
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 96, in start
    streams = await asyncio.get_event_loop().run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "c:\Program Files\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 98, in <lambda>
    lambda: self.streamlink.streams(f"https://www.twitch.tv/{self.channel}")
            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\session.py", line 153, in streams
    return plugin.streams(**params)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugin\plugin.py", line 401, in streams
    ostreams = self._get_streams()
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 986, in _get_streams
    return self._get_hls_streams_live()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 915, in _get_hls_streams_live
    sig, token, restricted_bitrates = self._access_token(True, self.channel)
                                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 884, in _access_token
    response, *data = self.api.access_token(is_live, channel_or_vod)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 516, in access_token
    return self.call(
           ~~~~~~~~~^
        query,
        ^^^^^^
    ...<29 lines>...
        ),
        ^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 314, in call
    return self.session.http.post(
           ~~~~~~~~~~~~~~~~~~~~~~^
        "https://gql.twitch.tv/gql",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\http.py", line 196, in request
    raise err from None  # TODO: fix this
    ^^^^^^^^^^^^^^^^^^^
streamlink.exceptions.PluginError: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6841E50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
[2025-05-18 02:51:59] [error] [BOT 2] Fatal error: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6842D50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
Traceback (most recent call last):
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 96, in start
    streams = await asyncio.get_event_loop().run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "c:\Program Files\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 98, in <lambda>
    lambda: self.streamlink.streams(f"https://www.twitch.tv/{self.channel}")
            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\session.py", line 153, in streams
    return plugin.streams(**params)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugin\plugin.py", line 401, in streams
    ostreams = self._get_streams()
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 986, in _get_streams
    return self._get_hls_streams_live()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 915, in _get_hls_streams_live
    sig, token, restricted_bitrates = self._access_token(True, self.channel)
                                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 884, in _access_token
    response, *data = self.api.access_token(is_live, channel_or_vod)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 516, in access_token
    return self.call(
           ~~~~~~~~~^
        query,
        ^^^^^^
    ...<29 lines>...
        ),
        ^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 314, in call
    return self.session.http.post(
           ~~~~~~~~~~~~~~~~~~~~~~^
        "https://gql.twitch.tv/gql",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\http.py", line 196, in request
    raise err from None  # TODO: fix this
    ^^^^^^^^^^^^^^^^^^^
streamlink.exceptions.PluginError: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6842D50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
[2025-05-18 02:51:59] [error] [BOT 3] Fatal error: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6842210>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
Traceback (most recent call last):
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 96, in start
    streams = await asyncio.get_event_loop().run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "c:\Program Files\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 98, in <lambda>
    lambda: self.streamlink.streams(f"https://www.twitch.tv/{self.channel}")
            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\session.py", line 153, in streams
    return plugin.streams(**params)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugin\plugin.py", line 401, in streams
    ostreams = self._get_streams()
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 986, in _get_streams
    return self._get_hls_streams_live()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 915, in _get_hls_streams_live
    sig, token, restricted_bitrates = self._access_token(True, self.channel)
                                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 884, in _access_token
    response, *data = self.api.access_token(is_live, channel_or_vod)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 516, in access_token
    return self.call(
           ~~~~~~~~~^
        query,
        ^^^^^^
    ...<29 lines>...
        ),
        ^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 314, in call
    return self.session.http.post(
           ~~~~~~~~~~~~~~~~~~~~~~^
        "https://gql.twitch.tv/gql",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\http.py", line 196, in request
    raise err from None  # TODO: fix this
    ^^^^^^^^^^^^^^^^^^^
streamlink.exceptions.PluginError: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6842210>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
